[package]
name = "hello"
version = "0.1.0"
authors = ["liukangcc <liukangcc@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "hello"
crate-type = ["staticlib"]
path = "src/lib.rs"
